name: CI/CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Configure
      run: |
        sudo apt-get update 
        sudo apt-get upgrade

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.0.0

    - name: Build
      run: make all | chmod +x ./output/IPGwidgetApp

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: IPGwidgetApp.0.1-${{ github.run_number }}
        release_name: IPGwidgetApp.0.1-${{ github.run_number }}
        draft: false
        prerelease: false
        body: |
          Target platform: ${{ runner.os }}
          Target architecture: ${{ runner.arch }}

    - name: Upload Executable
      id: upload-executable 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./output/IPGwidgetApp
        asset_name: IPGwidgetApp
        asset_content_type: binary/application
